version: "3"

services:
  app:
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.2.0-devel-ubuntu20.04
        - PYTHON_VERSION=3.11
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    volumes:
      - ../app:/home/paper_translator/
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
